import test from 'node:test';
import assert from 'node:assert/strict';
import {bossStart,play,endTurn,intent} from '../lib/battle.ts';
import {chooseGift} from '../lib/journey.ts';
test('well offers capped healing or a permanent boss gift without healing',()=>{assert.deepEqual(chooseGift(30,'none','heal'),{hp:36,relic:'none'});assert.deepEqual(chooseGift(18,'none','heal'),{hp:32,relic:'none'});assert.deepEqual(chooseGift(18,'none','ember'),{hp:18,relic:'ember'});assert.deepEqual(chooseGift(18,'none','ward'),{hp:18,relic:'ward'});});
test('boss carries health, refreshes starter deck and forecasts rage exactly',()=>{let s=bossStart(23,'none');assert.equal(s.hp,23);assert.equal(s.enemies.length,1);assert.equal(s.hand.length+s.deck.length,10);assert.deepEqual([1,2,3,4].map(turn=>intent({...s,turn},0).damage),[8,0,12,6]);s={...s,enemies:[{...s.enemies[0],hp:36}]};assert.deepEqual([1,2,3,4].map(turn=>intent({...s,turn},0).damage),[11,0,15,9]);});
test('ember strengthens attacks and mirror while ward replenishes instead of stacking',()=>{let s=bossStart(30,'ember');s=play(play(s,3),0,0);assert.equal(s.enemies[0].hp,60);s=bossStart(30,'ward');assert.equal(s.block,3);s=endTurn(play(s,1));assert.equal(s.hp,30);assert.equal(s.block,3);s=endTurn(play(s,6));assert.equal(s.block,3);});
function bestTurn(s){const options=[];function visit(current){options.push(current);if(current.status!=='playing')return;for(const c of current.hand){const next=play(current,c.id,0);if(next!==current)visit(next);}}visit(s);return options.sort((a,b)=>{const score=x=>x.status==='won'?10000:((72-x.enemies[0].hp)*2+endTurn(x).hp*3);return score(b)-score(a);})[0];}
test('each gift has a viable boss line, but passing turns loses',()=>{for(const relic of ['none','ember','ward']){let s=bossStart(30,relic);for(let t=0;t<15&&s.status==='playing';t++){s=bestTurn(s);if(s.status==='playing')s=endTurn(s);}assert.equal(s.status,'won',relic);assert.ok(s.hp>0);console.log(`${relic}: ${s.turn} turns, ${s.hp} hp`);}let s=bossStart(36,'ward');for(let i=0;i<20&&s.status==='playing';i++)s=endTurn(s);assert.equal(s.status,'lost');});
