import React,{useEffect,useRef} from 'react';
import {Animated,View,StyleSheet,Pressable,PressableProps} from 'react-native';
import Svg,{Defs,ClipPath,Polygon,Image as SvgImage,Path} from 'react-native-svg';
import {Image} from 'expo-image';
import {picture,source} from '../lib/assets';
import {CardKey} from '../lib/battle';
import {EnemyFlavor,deathDuration} from '../lib/character';
export function DeathRemains({flavor,size,reduced}:{flavor:EnemyFlavor,size:number,reduced:boolean}){
 const a=useRef(new Animated.Value(reduced?1:0)).current;
 useEffect(()=>{const anim=Animated.timing(a,{toValue:1,duration:reduced?0:deathDuration(flavor),useNativeDriver:true});anim.start();return()=>anim.stop();},[a,flavor,reduced]);
 return <View pointerEvents="none" style={StyleSheet.absoluteFill}>{flavor==='dune'?<>{Array.from({length:14},(_,i)=><Animated.View key={i} style={{position:'absolute',bottom:2,left:size*.45,width:6+i%4*3,height:3+i%3,borderRadius:6,backgroundColor:'#c6a975',opacity:a.interpolate({inputRange:[0,.2,.6,1],outputRange:[0,.7,.5,.28]}),transform:[{translateX:a.interpolate({inputRange:[0,1],outputRange:[0,(i-7)*size*.055]})},{translateY:a.interpolate({inputRange:[0,.4,1],outputRange:[-size*.25,-15,0]})}]}}/>)}</>:<Animated.View style={{width:size,height:size,opacity:a.interpolate({inputRange:[0,.15,.5,1],outputRange:[0,1,1,.7]}),transformOrigin:'25% 95%',transform:[{translateY:a.interpolate({inputRange:[0,1],outputRange:[-size*.25,size*.12]})},{rotate:a.interpolate({inputRange:[0,.6,1],outputRange:['0deg','-73deg','-70deg']})},{scale:.67}]}}><Svg width={size} height={size} viewBox="0 0 100 100"><Defs><ClipPath id={`fallen-${flavor}`}><Polygon points={flavor==='boss'?'0,0 30,0 33,78 17,84 0,40':'0,0 18,0 33,88 28,91 5,38'}/></ClipPath></Defs><SvgImage href={source(flavor==='boss'?'boss':'enemy')} width={100} height={100} clipPath={`url(#fallen-${flavor})`}/></Svg></Animated.View>}</View>;
}
export function BellCracks({size,dead=false}:{size:number,dead?:boolean}){return <Svg pointerEvents="none" width={size} height={size} style={StyleSheet.absoluteFill} viewBox="0 0 100 100"><Path d="M46 5 49 13 45 18 50 25 47 30 M59 12 57 18 63 22 61 28" stroke={dead?'#fff4cd':'#ffb957'} strokeWidth={dead?1.4:.8} fill="none"/></Svg>;}
export type Cast={serial:number,key:CardKey,x:number,y:number,toX:number,toY:number,size:number};
export function CardEffect({cast,reduced}:{cast:Cast,reduced:boolean}){
 const a=useRef(new Animated.Value(0)).current;useEffect(()=>{a.setValue(0);const anim=Animated.timing(a,{toValue:1,duration:750,useNativeDriver:true});anim.start();return()=>anim.stop();},[cast.serial,a]);
 const opacity=a.interpolate({inputRange:[0,.2,.35,.65,1],outputRange:[0,.2,1,.7,0]}),dx=cast.toX-cast.x,dy=cast.toY-cast.y;
 if(cast.key==='mirror')return <Animated.View pointerEvents="none" style={{position:'absolute',left:cast.x-cast.size/2,top:cast.y-cast.size*.6,width:cast.size,height:cast.size,zIndex:4,opacity,transform:reduced?[]:[{translateX:a.interpolate({inputRange:[0,1],outputRange:[0,-35]})}]}}><Image source={picture('hero')} tintColor="#a9e8ed" style={{width:cast.size,height:cast.size}}/></Animated.View>;
 if(cast.key==='veil')return <Animated.View pointerEvents="none" style={{position:'absolute',left:cast.x-cast.size*.5,top:cast.y-cast.size*.7,zIndex:7,opacity,transform:reduced?[]:[{translateY:a.interpolate({inputRange:[0,1],outputRange:[25,-18]})}]}}><Svg width={cast.size} height={cast.size} viewBox="0 0 100 100"><Path d="M20 85Q80 70 20 60Q80 45 30 30 M30 95Q90 80 30 70Q90 50 40 20" stroke="#f4e8ba" strokeWidth={2} fill="none"/></Svg></Animated.View>;
 return <Animated.View pointerEvents="none" style={{position:'absolute',left:cast.key==='pierce'?cast.x:cast.toX-cast.size*.3,top:cast.key==='pierce'?cast.y:cast.toY-cast.size*.15,zIndex:9,opacity,transform:reduced?[]:cast.key==='pierce'?[{translateX:a.interpolate({inputRange:[0,.35,1],outputRange:[0,dx,dx+20]})},{translateY:a.interpolate({inputRange:[0,.35,1],outputRange:[0,dy,dy]})},{rotate:`${Math.atan2(dy,dx)*180/Math.PI}deg`}]:[{rotate:'-28deg'},{scaleX:a.interpolate({inputRange:[0,.35,1],outputRange:[.1,1,1.3]})}]}}>{cast.key==='pierce'?<><View style={{width:90,height:3,backgroundColor:'#fff0a9'}}/><View style={{position:'absolute',left:45,top:-3,width:35,height:9,backgroundColor:'#ffe9a599'}}/></>:<Svg width={cast.size*.7} height={45} viewBox="0 0 100 45"><Path d="M0 30 88 3 100 5 20 36Z M32 35 47 39 66 30 M73 17 88 22 96 13" fill="#d7fff0"/></Svg>}</Animated.View>;
}
export function IntentButton({revision,reduced,children,...props}:PressableProps&{revision:string,reduced:boolean}){const a=useRef(new Animated.Value(1)).current;useEffect(()=>{if(reduced)return;a.setValue(.72);const anim=Animated.spring(a,{toValue:1,speed:22,bounciness:7,useNativeDriver:true});anim.start();return()=>anim.stop();},[revision,reduced,a]);return <Pressable {...props}><Animated.View style={{transform:[{scale:a}],alignItems:'center',justifyContent:'center'}}>{typeof children==='function'?null:children}</Animated.View></Pressable>;}
