import React,{useEffect,useRef} from 'react';
import {Animated,Easing,Pressable,StyleSheet,Text,View} from 'react-native';
import Svg,{Path,Circle} from 'react-native-svg';
import {Relic,HERO_HP} from '../lib/battle';
export type Reward='heal'|'ember'|'ward';
export function Torchlight({reduced=false}:{reduced?:boolean}){
 const pulse=useRef(new Animated.Value(0)).current;
 useEffect(()=>{if(reduced)return;const a=Animated.loop(Animated.sequence([Animated.timing(pulse,{toValue:1,duration:370,useNativeDriver:true}),Animated.timing(pulse,{toValue:.35,duration:210,useNativeDriver:true}),Animated.timing(pulse,{toValue:.8,duration:450,useNativeDriver:true}),Animated.timing(pulse,{toValue:0,duration:320,useNativeDriver:true})]));a.start();return()=>a.stop();},[reduced,pulse]);
 return <View pointerEvents="none" style={StyleSheet.absoluteFill}>{[false,true].map((right,i)=><View key={i} style={{position:'absolute',top:'35%',left:right?undefined:'10%',right:right?'10%':undefined,width:30,height:100}}><Animated.View style={{position:'absolute',width:210,height:210,left:-90,top:-92,borderRadius:110,backgroundColor:'#e59226',opacity:pulse.interpolate({inputRange:[0,1],outputRange:[.07,.16]}),transform:[{scale:pulse.interpolate({inputRange:[0,1],outputRange:[.95,1.13]})}]}}/><View style={{width:9,height:62,top:30,left:10,backgroundColor:'#5b4532',borderWidth:2,borderColor:'#ad8852',transform:[{rotate:right?'-9deg':'9deg'}]}}/><Animated.View style={{position:'absolute',top:2,left:3,width:24,height:40,borderTopLeftRadius:22,borderTopRightRadius:6,borderBottomLeftRadius:14,borderBottomRightRadius:14,backgroundColor:'#ed9f39',opacity:pulse.interpolate({inputRange:[0,1],outputRange:[.7,1]}),transform:[{scaleY:pulse.interpolate({inputRange:[0,1],outputRange:[.85,1.12]})},{rotate:pulse.interpolate({inputRange:[0,1],outputRange:['-7deg','7deg']})}]}}><View style={{position:'absolute',width:10,height:22,bottom:3,left:7,borderRadius:8,backgroundColor:'#ffe0a0'}}/></Animated.View></View>)}</View>;
}
export function Button({title,onPress,disabled=false}:{title:string,onPress:()=>void,disabled?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,{opacity:disabled?.45:pressed?.7:1}]}><Text style={s.buttonText}>{title}</Text></Pressable>;}
export function Title({ready,error,onStart,onRetry,reduced}:{ready:boolean,error:boolean,onStart:()=>void,onRetry:()=>void,reduced:boolean}){return <View style={s.screen}><Torchlight reduced={reduced}/><Text style={s.eyebrow}>A LITTLE ASCENT</Text><Text style={s.title}>Andrew the Spire</Text><View style={s.rule}/><Button title={error?'Retry loading':'Start Game'} disabled={!ready&&!error} onPress={error?onRetry:onStart}/>{!ready&&<Text accessibilityLiveRegion="polite" style={s.caption}>{error?'Could not load the game.':'Kindling the fire…'}</Text>}</View>;}
export function MapScreen({step,hp,relic,onEnter,reduced}:{step:number,hp:number,relic:Relic,onEnter:()=>void,reduced:boolean}){return <View style={s.screen}><Torchlight reduced={reduced}/><Text style={s.eyebrow}>THE GLASS ASCENT</Text><Text style={s.heading}>A road through the eclipse</Text><View style={{width:'68%',height:155,marginTop:8}}><Svg width="100%" height="100%" viewBox="0 0 600 150" preserveAspectRatio="none"><Path d="M80 86 C160 145 205 18 300 53 S450 140 520 65" stroke="#bda274" strokeWidth={2} strokeDasharray="4 7" fill="none"/></Svg>{['Crossing','The wishing well','The Bellkeeper'].map((name,i)=><Pressable key={name} accessibilityRole="button" accessibilityLabel={`${name}${i<step?', completed':i===step?', next room':', locked'}`} disabled={i!==step} onPress={onEnter} style={{position:'absolute',left:`${[13.3,50,86.6][i]}%`,top:[54,21,33][i],width:130,marginLeft:-65,alignItems:'center',opacity:i>step?.35:1}}><View style={[s.node,i===step&&{borderColor:'#ffe5a6',backgroundColor:'#485345',transform:[{scale:1.12}]}]}><Text style={s.nodeText}>{i<step?'✓':['⚔','?','♛'][i]}</Text></View><Text style={s.caption}>{name}</Text></Pressable>)}</View><Text style={s.caption}>{hp} / {HERO_HP} health{relic!=='none'?`  ·  ${relic==='ember'?'Sun ember':'Ivory charm'}`:''}</Text><Button title={step===0?'Enter the crossing':step===1?'Visit the well':'Face the Bellkeeper'} onPress={onEnter}/></View>;}
export function BonusRoom({hp,onChoose,reduced}:{hp:number,onChoose:(r:Reward)=>void,reduced:boolean}){return <View style={s.screen}><Torchlight reduced={reduced}/><Text style={[s.eyebrow,{fontSize:32}]}>?</Text><Text style={s.heading}>The well asks for a wish.</Text><Text style={s.caption}>Take one gift.</Text><View style={{flexDirection:'row',gap:14,marginTop:22,width:'75%'}}>{([{key:'heal',symbol:'♡',title:'Moonwater',text:`Heal ${Math.min(14,HERO_HP-hp)} health`},{key:'ember',symbol:'✦',title:'Sun ember',text:'Every attack +2 damage'},{key:'ward',symbol:'◇',title:'Ivory charm',text:'Start each turn with 3 block'}] as const).map(r=><Pressable key={r.key} accessibilityRole="button" onPress={()=>onChoose(r.key)} style={({pressed})=>[s.gift,{backgroundColor:pressed?'#344a46':'#102c32'}]}><Text style={s.symbol}>{r.symbol}</Text><Text style={s.giftTitle}>{r.title}</Text><Text style={s.caption}>{r.text}</Text></Pressable>)}</View></View>;}
export function Finale({hp,turns,onAgain,reduced}:{hp:number,turns:number,onAgain:()=>void,reduced:boolean}){
 const rise=useRef(new Animated.Value(reduced?1:0)).current;
 useEffect(()=>{const a=Animated.timing(rise,{toValue:1,duration:4200,easing:Easing.out(Easing.cubic),useNativeDriver:true});a.start();return()=>a.stop();},[rise]);
 return <View style={[s.screen,{backgroundColor:'#162f36'}]}><View pointerEvents="none" style={StyleSheet.absoluteFill}><Animated.View style={{position:'absolute',left:'50%',top:'42%',marginLeft:-72,marginTop:-72,width:144,height:144,borderRadius:80,backgroundColor:'#f0c36d',opacity:rise,transform:[{scale:rise.interpolate({inputRange:[0,1],outputRange:[.1,3.5]})}]}}/><Animated.View style={{position:'absolute',left:'50%',top:'42%',marginLeft:-69,marginTop:-69,width:138,height:138,borderRadius:80,backgroundColor:'#09242d',transform:[{translateX:rise.interpolate({inputRange:[0,1],outputRange:[0,180]})},{translateY:rise.interpolate({inputRange:[0,1],outputRange:[0,-210]})}]}}/>{Array.from({length:30},(_,i)=><Animated.View key={i} style={{position:'absolute',left:'50%',top:'42%',width:4+i%4,height:12+i%7,backgroundColor:i%2?'#f2d492':'#fff4ce',opacity:rise.interpolate({inputRange:[0,.2,1],outputRange:[0,1,.3]}),transform:[{translateX:rise.interpolate({inputRange:[0,1],outputRange:[0,Math.cos(i*2.4)*(180+i*8)]})},{translateY:rise.interpolate({inputRange:[0,1],outputRange:[0,Math.sin(i*2.4)*(140+i*6)]})},{rotate:`${i*47}deg`}]}}/>)}</View><Animated.View style={{alignItems:'center',opacity:rise.interpolate({inputRange:[0,.45,1],outputRange:[0,0,1]}),backgroundColor:'#09242dce',padding:24,borderRadius:12}}><Text style={s.eyebrow}>THE BELL FALLS SILENT</Text><Text style={s.title}>You stole back the sun.</Text><Text style={s.caption}>{turns} turns · {hp} health remaining</Text><Button title="One more ascent" onPress={onAgain}/></Animated.View></View>;
}
const s=StyleSheet.create({screen:{...StyleSheet.absoluteFill,backgroundColor:'#081c25',alignItems:'center',justifyContent:'center',zIndex:70},eyebrow:{fontSize:11,fontWeight:'800',letterSpacing:4,color:'#c39c59',marginBottom:12},title:{fontSize:38,fontWeight:'900',color:'#f5dfaf',textAlign:'center',letterSpacing:-1},heading:{fontSize:25,fontWeight:'800',color:'#f5dfaf',textAlign:'center'},rule:{width:65,height:1,backgroundColor:'#b59b68',margin:20},button:{minHeight:46,marginTop:12,paddingHorizontal:27,paddingVertical:12,borderWidth:1,borderColor:'#c3a56b',backgroundColor:'#283d3c',borderRadius:5},buttonText:{color:'#ffe5b6',fontSize:16,fontWeight:'800'},caption:{color:'#cfc3a8',fontSize:12,textAlign:'center',marginTop:9},node:{width:55,height:55,borderRadius:30,borderWidth:2,borderColor:'#8f835f',backgroundColor:'#0b222b',alignItems:'center',justifyContent:'center'},nodeText:{fontSize:28,color:'#eed198'},gift:{flex:1,minHeight:135,padding:14,alignItems:'center',borderWidth:1,borderColor:'#9b865a',borderRadius:8},symbol:{fontSize:35,color:'#ebc47d'},giftTitle:{fontSize:16,fontWeight:'800',color:'#f5dfaf',marginTop:8}});
